/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_data_CppDataStore */

#ifndef _Included_example_data_CppDataStore
#define _Included_example_data_CppDataStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_data_CppDataStore
 * Method:    storeData
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_example_data_CppDataStore_storeData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
